export const types = {
  APPEND: "APPEND",
  EDIT: "EDIT",
  CLEAN: "CLEAN",
  FETCH: "FETCH",
  DELETE: "DELETE",
  CHANGE_TO_EDIT: "CHANGE_TO_EDIT",
  UPDATE: "UPDATE",
  TRUE_SPINNER: "TRUE_SPINNER",
  FALSE_SPINNER: "FALSE_SPINNER",
  TRUE_MODAL: "TRUE_MODAL",
  FALSE_MODAL: "FALSE_MODAL",
};
